language: php
php:
  - '5.5'
  - '7.0'
before_script:
  - composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: false
